### ISSUE TITLE
Looking for Assets Folder?

### ISSUE THREAD

**Issue by mvdesign** [ThorntonStuart/SimpleCloner#6]
I'm trying out SimpleCloner for the first time today (EE 3.5.3). It seems to work fine on a few of my simpler channels. Unfortunately, on the one channel I really want to use it, I'm getting an error when I try to clone the entry:

```
Array ( [Wine] => The following field is required: )

Exception Caught

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.exp_assets_folders' doesn't exist:
SELECT * FROM (`exp_assets_folders`) WHERE `folder_name` = 27

ee/legacy/database/drivers/mysqli/mysqli_connection.php:122
```

For what it's worth, Wine is a relationship field. I do not have Assets installed. I'm using Ansel and the native EE File Manager with my images.

This channel is admittedly a fairly complicated one. It's got about 35 fields, including:    
* relationship
* text
* wygwam
* grid (with date and toggle columns)
* publish_notes
* ansel
* url

Here is the Stack Trace, if that's of any assistance:

```
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(137): CI_DB_mysqli_connection->query('SELECT *\nFROM (...')
#1 ee/legacy/database/DB_driver.php(297): CI_DB_mysqli_driver->_execute('SELECT *\nFROM (...')
#2 ee/legacy/database/DB_driver.php(203): CI_DB_driver->simple_query('SELECT *\nFROM (...')
#3 ee/legacy/database/DB_active_rec.php(1219): CI_DB_driver->query('SELECT *\nFROM (...')
#4 user/addons/simple_cloner/ext.simple_cloner.php(522): CI_DB_active_record->get()
#5 user/addons/simple_cloner/ext.simple_cloner.php(576): Simple_cloner_ext->generate_new_ansel_image(Array, 27, '46')
#6 user/addons/simple_cloner/ext.simple_cloner.php(290): Simple_cloner_ext->duplicate_ansel(Object(CI_DB_mysqli_result), 78)
#7 ee/legacy/libraries/Extensions.php(243): Simple_cloner_ext->simple_cloner_content_save(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#8 ee/legacy/libraries/Extensions.php(138): EE_Extensions->call_class('Simple_cloner_e...', 'after_channel_e...', Array, Array)
#9 [internal function]: EE_Extensions->call('after_channel_e...', Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#10 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(642): call_user_func_array(Array, Array)
#11 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->EllisLab\ExpressionEngine\Service\Model\{closure}('after_channel_e...', Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#12 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(615): call_user_func_array(Object(Closure), Array)
#13 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->EllisLab\ExpressionEngine\Service\Model\{closure}()
#14 ee/EllisLab/ExpressionEngine/Service/Event/Emitter.php(153): call_user_func_array(Object(Closure), Array)
#15 [internal function]: EllisLab\ExpressionEngine\Service\Event\Emitter->emit('afterSave')
#16 ee/EllisLab/ExpressionEngine/Library/Data/Entity.php(629): call_user_func_array(Array, Array)
#17 [internal function]: EllisLab\ExpressionEngine\Library\Data\Entity->emit('afterSave')
#18 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(834): call_user_func_array('parent::emit', Array)
#19 ee/EllisLab/ExpressionEngine/Service/Model/Query/Update.php(60): EllisLab\ExpressionEngine\Service\Model\Model->emit('afterSave')
#20 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(294): EllisLab\ExpressionEngine\Service\Model\Query\Update->run()
#21 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(260): EllisLab\ExpressionEngine\Service\Model\DataStore->runQuery('Update', Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
#22 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(83): EllisLab\ExpressionEngine\Service\Model\DataStore->updateQuery(Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
#23 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(366): EllisLab\ExpressionEngine\Service\Model\Query\Builder->update()
#24 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(198): EllisLab\ExpressionEngine\Service\Model\Model->save()
#25 ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php(295): EllisLab\ExpressionEngine\Model\Content\ContentModel->save()
#26 ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.php(482): EllisLab\ExpressionEngine\Controller\Publish\AbstractPublish->saveEntryAndRedirect(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry))
#27 [internal function]: EllisLab\ExpressionEngine\Controller\Publish\Edit->entry('32')
#28 ee/EllisLab/ExpressionEngine/Core/Core.php(189): call_user_func_array(Array, Array)
#29 ee/EllisLab/ExpressionEngine/Core/Core.php(94): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#30 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#31 html/mmdcms/index.php(143): require_once('...')
#31 html/mmdcms/index.php(143): require_once('...')
```

Thanks for your time.

**Comment by ThorntonStuart** [comment]
It looks as though there may be a missed check for an Assets install. Will take a look now and get back to you.

**Comment by mvdesign** [comment]
Thanks! I appreciate it. Let me know if you need any additional info or access from me.

**Comment by ThorntonStuart** [comment]
Hi @mvdesign. Sorry for the delay I am waiting to hear from EEHarbor about acquiring a test copy of Assets so that I can get to the bottom of this properly.

**Comment by mvdesign** [comment]
Thanks for the update. Let me know if it would be helpful for me to nudge them as well.

**Comment by mvdesign** [comment]
I got a fix from Peter over Slack that seems to have cleared up this error message. I'm still getting an error for this channel, but it's a different error. I'll open up a new issue for that, and I think you can feel free to roll Peter's fix into the module and close this issue as solved. Thanks!
